BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS public.task (
	id UUID DEFAULT gen_random_uuid(),
	task VARCHAR(300) NOT NULL,
	is_public BOOLEAN NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_email TEXT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.comment (
	id UUID DEFAULT gen_random_uuid(),
	comment VARCHAR(300) NOT NULL,
	task_id UUID NOT NULL,
	user_name TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_email TEXT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(task_id) REFERENCES task(id)
);

COMMIT;

